version: '3'

services:

  db:
    image: postgres:12
    container_name: db
    restart: always
    tty: true
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=taskmanager
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
  
volumes:
  postgres:
    external: true